# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["defaults" "size=4G" "mode=755"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/374D-5C0E";
    fsType = "vfat";
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/nixos";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  boot.initrd.luks.devices."nixos".device = "/dev/disk/by-uuid/1168c941-c120-4b93-952e-2d50e4c80aa1";

  fileSystems."/etc" = {
    device = "/dev/mapper/nixos";
    fsType = "btrfs";
    options = ["subvol=etc"];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/nixos";
    fsType = "btrfs";
    options = ["subvol=log"];
  };

  fileSystems."/root" = {
    device = "/dev/mapper/nixos";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/nixos";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/var/lib" = {
    device = "/dev/mapper/nixos";
    fsType = "btrfs";
    options = ["subvol=lib"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/1f39d95c-191c-4089-8289-dad533d6bbe3";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
